import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Inter } from "next/font/google";
import Container from "./container";
import BackgroundGradient from "@/components/background/BackgroundGradient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`antialiased ${inter.className}`}
      >
        <Navbar />
        <main className="py-10">
          <BackgroundGradient />
          <Container>
            {children}
          </Container>
        </main>
        <Footer />
      </body>
    </html>
  );
}
